version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/index
      - /index/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=qwerty12345
    command: npm run dev

  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run start
